#request
{ invokeWithLayer
  layer: 146 [INT],
  query: { initConnection
    flags: 2 [INT],
    api_id: 17349 [INT],
    device_model: "Alienware 15 R4" [STRING],
    system_version: "Windows 10" [STRING],
    app_version: "4.2.4 x64" [STRING],
    system_lang_code: "zh-CN" [STRING],
    lang_pack: "tdesktop" [STRING],
    lang_code: "zh_CN" [STRING],
    proxy: [ SKIPPED BY BIT 0 IN FIELD flags ],
    params: { jsonObject
      value: [ vector<0x0> (1)
        { jsonObjectValue
          key: "tz_offset" [STRING],
          value: { jsonNumber
            value: 28800 [DOUBLE],
          },
        },
      ],
    },
    query: { users_getFullUser
      id: { inputUserSelf },
    },
  },
},
#respons
{ rpc_result
  req_msg_id: 7223220221938836060 [LONG],
  result: { users_userFull
    full_user: { userFull
      flags: 6299792 [INT],
      blocked: [ SKIPPED BY BIT 0 IN FIELD flags ],
      phone_calls_available: YES [ BY BIT 4 IN FIELD flags ],
      phone_calls_private: [ SKIPPED BY BIT 5 IN FIELD flags ],
      can_pin_message: YES [ BY BIT 7 IN FIELD flags ],
      has_scheduled: [ SKIPPED BY BIT 12 IN FIELD flags ],
      video_calls_available: YES [ BY BIT 13 IN FIELD flags ],
      voice_messages_forbidden: [ SKIPPED BY BIT 20 IN FIELD flags ],
      id: 136909671 [LONG],
      about: [ SKIPPED BY BIT 1 IN FIELD flags ],
      settings: { peerSettings
        flags: 0 [INT],
        report_spam: [ SKIPPED BY BIT 0 IN FIELD flags ],
        add_contact: [ SKIPPED BY BIT 1 IN FIELD flags ],
        block_contact: [ SKIPPED BY BIT 2 IN FIELD flags ],
        share_contact: [ SKIPPED BY BIT 3 IN FIELD flags ],
        need_contacts_exception: [ SKIPPED BY BIT 4 IN FIELD flags ],
        report_geo: [ SKIPPED BY BIT 5 IN FIELD flags ],
        autoarchived: [ SKIPPED BY BIT 7 IN FIELD flags ],
        invite_members: [ SKIPPED BY BIT 8 IN FIELD flags ],
        request_chat_broadcast: [ SKIPPED BY BIT 10 IN FIELD flags ],
        geo_distance: [ SKIPPED BY BIT 6 IN FIELD flags ],
        request_chat_title: [ SKIPPED BY BIT 9 IN FIELD flags ],
        request_chat_date: [ SKIPPED BY BIT 9 IN FIELD flags ],
      },
      profile_photo: [ SKIPPED BY BIT 2 IN FIELD flags ],
      notify_settings: { peerNotifySettings
        flags: 0 [INT],
        show_previews: [ SKIPPED BY BIT 0 IN FIELD flags ],
        silent: [ SKIPPED BY BIT 1 IN FIELD flags ],
        mute_until: [ SKIPPED BY BIT 2 IN FIELD flags ],
        ios_sound: [ SKIPPED BY BIT 3 IN FIELD flags ],
        android_sound: [ SKIPPED BY BIT 4 IN FIELD flags ],
        other_sound: [ SKIPPED BY BIT 5 IN FIELD flags ],
      },
      bot_info: [ SKIPPED BY BIT 3 IN FIELD flags ],
      pinned_msg_id: [ SKIPPED BY BIT 6 IN FIELD flags ],
      common_chats_count: 0 [INT],
      folder_id: [ SKIPPED BY BIT 11 IN FIELD flags ],
      ttl_period: [ SKIPPED BY BIT 14 IN FIELD flags ],
      theme_emoticon: [ SKIPPED BY BIT 15 IN FIELD flags ],
      private_forward_name: [ SKIPPED BY BIT 16 IN FIELD flags ],
      bot_group_admin_rights: [ SKIPPED BY BIT 17 IN FIELD flags ],
      bot_broadcast_admin_rights: [ SKIPPED BY BIT 18 IN FIELD flags ],
      premium_gifts: [ SKIPPED BY BIT 19 IN FIELD flags ],
      sex: 1 [INT],
      birth_data: 1681401600 [INT],
      contact_source: [ SKIPPED BY BIT 23 IN FIELD flags ],
      contact_source_ext: [ SKIPPED BY BIT 24 IN FIELD flags ],
    },
    chats: [ vector<0x0> (0) ],
    users: [ vector<0x0> (1)
      { user
        flags: 7243 [INT],
        self: YES [ BY BIT 10 IN FIELD flags ],
        contact: YES [ BY BIT 11 IN FIELD flags ],
        mutual_contact: YES [ BY BIT 12 IN FIELD flags ],
        deleted: [ SKIPPED BY BIT 13 IN FIELD flags ],
        bot: [ SKIPPED BY BIT 14 IN FIELD flags ],
        bot_chat_history: [ SKIPPED BY BIT 15 IN FIELD flags ],
        bot_nochats: [ SKIPPED BY BIT 16 IN FIELD flags ],
        verified: [ SKIPPED BY BIT 17 IN FIELD flags ],
        restricted: [ SKIPPED BY BIT 18 IN FIELD flags ],
        min: [ SKIPPED BY BIT 20 IN FIELD flags ],
        bot_inline_geo: [ SKIPPED BY BIT 21 IN FIELD flags ],
        support: [ SKIPPED BY BIT 23 IN FIELD flags ],
        scam: [ SKIPPED BY BIT 24 IN FIELD flags ],
        apply_min_photo: [ SKIPPED BY BIT 25 IN FIELD flags ],
        fake: [ SKIPPED BY BIT 26 IN FIELD flags ],
        bot_attach_menu: [ SKIPPED BY BIT 27 IN FIELD flags ],
        premium: [ SKIPPED BY BIT 28 IN FIELD flags ],
        attach_menu_enabled: [ SKIPPED BY BIT 29 IN FIELD flags ],
        id: 136909671 [LONG],
        access_hash: 1396098147761448440 [LONG],
        first_name: "Debbie" [STRING],
        last_name: [ SKIPPED BY BIT 2 IN FIELD flags ],
        username: "rgvcdd" [STRING],
        phone: [ SKIPPED BY BIT 4 IN FIELD flags ],
        photo: [ SKIPPED BY BIT 5 IN FIELD flags ],
        status: { userStatusOffline
          was_online: 1681727790 [INT],
        },
        bot_info_version: [ SKIPPED BY BIT 14 IN FIELD flags ],
        restriction_reason: [ SKIPPED BY BIT 18 IN FIELD flags ],
        bot_inline_placeholder: [ SKIPPED BY BIT 19 IN FIELD flags ],
        lang_code: [ SKIPPED BY BIT 22 IN FIELD flags ],
        emoji_status: [ SKIPPED BY BIT 30 IN FIELD flags ],
      },
    ],
  },
},