{ channel
  flags: 434432 [INT],
  creator: [ SKIPPED BY BIT 0 IN FIELD flags ],
  left: [ SKIPPED BY BIT 2 IN FIELD flags ],
  broadcast: [ SKIPPED BY BIT 5 IN FIELD flags ],
  verified: [ SKIPPED BY BIT 7 IN FIELD flags ],
  megagroup: YES [ BY BIT 8 IN FIELD flags ],
  restricted: [ SKIPPED BY BIT 9 IN FIELD flags ],
  signatures: [ SKIPPED BY BIT 11 IN FIELD flags ],
  min: [ SKIPPED BY BIT 12 IN FIELD flags ],
  scam: [ SKIPPED BY BIT 19 IN FIELD flags ],
  has_link: [ SKIPPED BY BIT 20 IN FIELD flags ],
  has_geo: [ SKIPPED BY BIT 21 IN FIELD flags ],
  slowmode_enabled: [ SKIPPED BY BIT 22 IN FIELD flags ],
  call_active: [ SKIPPED BY BIT 23 IN FIELD flags ],
  call_not_empty: [ SKIPPED BY BIT 24 IN FIELD flags ],
  fake: [ SKIPPED BY BIT 25 IN FIELD flags ],
  gigagroup: [ SKIPPED BY BIT 26 IN FIELD flags ],
  noforwards: [ SKIPPED BY BIT 27 IN FIELD flags ],
  join_to_send: [ SKIPPED BY BIT 28 IN FIELD flags ],
  join_request: [ SKIPPED BY BIT 29 IN FIELD flags ],
  id: 739 [LONG],
  access_hash: 7855999791724622998 [LONG],
  title: "自动加入群测试群组" [STRING],
  username: [ SKIPPED BY BIT 6 IN FIELD flags ],
  photo: { chatPhoto
    flags: 0 [INT],
    has_video: [ SKIPPED BY BIT 0 IN FIELD flags ],
    photo_id: 1646766913793036288 [LONG],
    stripped_thumb: [ SKIPPED BY BIT 1 IN FIELD flags ],
    dc_id: 1 [INT],
  },
  date: 1681355256 [INT],
  restriction_reason: [ SKIPPED BY BIT 9 IN FIELD flags ],
  admin_rights: [ SKIPPED BY BIT 14 IN FIELD flags ],
  banned_rights: { chatBannedRights
    flags: 132352 [INT],
    view_messages: [ SKIPPED BY BIT 0 IN FIELD flags ],
    send_messages: [ SKIPPED BY BIT 1 IN FIELD flags ],
    send_media: [ SKIPPED BY BIT 2 IN FIELD flags ],
    send_stickers: [ SKIPPED BY BIT 3 IN FIELD flags ],
    send_gifs: [ SKIPPED BY BIT 4 IN FIELD flags ],
    send_games: [ SKIPPED BY BIT 5 IN FIELD flags ],
    send_inline: [ SKIPPED BY BIT 6 IN FIELD flags ],
    embed_links: [ SKIPPED BY BIT 7 IN FIELD flags ],
    send_polls: YES [ BY BIT 8 IN FIELD flags ],
    change_info: YES [ BY BIT 10 IN FIELD flags ],
    invite_users: [ SKIPPED BY BIT 15 IN FIELD flags ],
    pin_messages: YES [ BY BIT 17 IN FIELD flags ],
    until_date: 0 [INT],
  },
  default_banned_rights: { chatBannedRights
    flags: 132352 [INT],
    view_messages: [ SKIPPED BY BIT 0 IN FIELD flags ],
    send_messages: [ SKIPPED BY BIT 1 IN FIELD flags ],
    send_media: [ SKIPPED BY BIT 2 IN FIELD flags ],
    send_stickers: [ SKIPPED BY BIT 3 IN FIELD flags ],
    send_gifs: [ SKIPPED BY BIT 4 IN FIELD flags ],
    send_games: [ SKIPPED BY BIT 5 IN FIELD flags ],
    send_inline: [ SKIPPED BY BIT 6 IN FIELD flags ],
    embed_links: [ SKIPPED BY BIT 7 IN FIELD flags ],
    send_polls: YES [ BY BIT 8 IN FIELD flags ],
    change_info: YES [ BY BIT 10 IN FIELD flags ],
    invite_users: [ SKIPPED BY BIT 15 IN FIELD flags ],
    pin_messages: YES [ BY BIT 17 IN FIELD flags ],
    until_date: 0 [INT],
  },
  participants_count: 222 [INT],
},