# request
{ contacts_getContacts
  hash: 0 [LONG],
},
# response
{ contacts_contacts
  contacts: [ vector<0x0> (3)
    { contact
      user_id: 136909562 [LONG],
      mutual: { boolTrue },
    },
    { contact
      user_id: 136909639 [LONG],
      mutual: { boolTrue },
    },
    { contact
      user_id: 136909646 [LONG],
      mutual: { boolTrue },
    },
  ],
  saved_count: 0 [INT],
  users: [ vector<0x0> (3)
    { user
      flags: 6219 [INT],
      self: [ SKIPPED BY BIT 10 IN FIELD flags ],
      contact: YES [ BY BIT 11 IN FIELD flags ],
      mutual_contact: YES [ BY BIT 12 IN FIELD flags ],
      deleted: [ SKIPPED BY BIT 13 IN FIELD flags ],
      bot: [ SKIPPED BY BIT 14 IN FIELD flags ],
      bot_chat_history: [ SKIPPED BY BIT 15 IN FIELD flags ],
      bot_nochats: [ SKIPPED BY BIT 16 IN FIELD flags ],
      verified: [ SKIPPED BY BIT 17 IN FIELD flags ],
      restricted: [ SKIPPED BY BIT 18 IN FIELD flags ],
      min: [ SKIPPED BY BIT 20 IN FIELD flags ],
      bot_inline_geo: [ SKIPPED BY BIT 21 IN FIELD flags ],
      support: [ SKIPPED BY BIT 23 IN FIELD flags ],
      scam: [ SKIPPED BY BIT 24 IN FIELD flags ],
      apply_min_photo: [ SKIPPED BY BIT 25 IN FIELD flags ],
      fake: [ SKIPPED BY BIT 26 IN FIELD flags ],
      bot_attach_menu: [ SKIPPED BY BIT 27 IN FIELD flags ],
      premium: [ SKIPPED BY BIT 28 IN FIELD flags ],
      attach_menu_enabled: [ SKIPPED BY BIT 29 IN FIELD flags ],
      id: 136909562 [LONG],
      access_hash: 7151667056043391905 [LONG],
      first_name: "gfff" [STRING],
      last_name: [ SKIPPED BY BIT 2 IN FIELD flags ],
      username: "qwert" [STRING],
      phone: [ SKIPPED BY BIT 4 IN FIELD flags ],
      photo: [ SKIPPED BY BIT 5 IN FIELD flags ],
      status: { userStatusOffline
        was_online: 1681354796 [INT],
      },
      bot_info_version: [ SKIPPED BY BIT 14 IN FIELD flags ],
      restriction_reason: [ SKIPPED BY BIT 18 IN FIELD flags ],
      bot_inline_placeholder: [ SKIPPED BY BIT 19 IN FIELD flags ],
      lang_code: [ SKIPPED BY BIT 22 IN FIELD flags ],
      emoji_status: [ SKIPPED BY BIT 30 IN FIELD flags ],
    },
    { user
      flags: 6219 [INT],
      self: [ SKIPPED BY BIT 10 IN FIELD flags ],
      contact: YES [ BY BIT 11 IN FIELD flags ],
      mutual_contact: YES [ BY BIT 12 IN FIELD flags ],
      deleted: [ SKIPPED BY BIT 13 IN FIELD flags ],
      bot: [ SKIPPED BY BIT 14 IN FIELD flags ],
      bot_chat_history: [ SKIPPED BY BIT 15 IN FIELD flags ],
      bot_nochats: [ SKIPPED BY BIT 16 IN FIELD flags ],
      verified: [ SKIPPED BY BIT 17 IN FIELD flags ],
      restricted: [ SKIPPED BY BIT 18 IN FIELD flags ],
      min: [ SKIPPED BY BIT 20 IN FIELD flags ],
      bot_inline_geo: [ SKIPPED BY BIT 21 IN FIELD flags ],
      support: [ SKIPPED BY BIT 23 IN FIELD flags ],
      scam: [ SKIPPED BY BIT 24 IN FIELD flags ],
      apply_min_photo: [ SKIPPED BY BIT 25 IN FIELD flags ],
      fake: [ SKIPPED BY BIT 26 IN FIELD flags ],
      bot_attach_menu: [ SKIPPED BY BIT 27 IN FIELD flags ],
      premium: [ SKIPPED BY BIT 28 IN FIELD flags ],
      attach_menu_enabled: [ SKIPPED BY BIT 29 IN FIELD flags ],
      id: 136909639 [LONG],
      access_hash: 1412546972706941384 [LONG],
      first_name: "Ggg11" [STRING],
      last_name: [ SKIPPED BY BIT 2 IN FIELD flags ],
      username: "ertuuj" [STRING],
      phone: [ SKIPPED BY BIT 4 IN FIELD flags ],
      photo: [ SKIPPED BY BIT 5 IN FIELD flags ],
      status: { userStatusOffline
        was_online: 1681538860 [INT],
      },
      bot_info_version: [ SKIPPED BY BIT 14 IN FIELD flags ],
      restriction_reason: [ SKIPPED BY BIT 18 IN FIELD flags ],
      bot_inline_placeholder: [ SKIPPED BY BIT 19 IN FIELD flags ],
      lang_code: [ SKIPPED BY BIT 22 IN FIELD flags ],
      emoji_status: [ SKIPPED BY BIT 30 IN FIELD flags ],
    },
    { user
      flags: 6219 [INT],
      self: [ SKIPPED BY BIT 10 IN FIELD flags ],
      contact: YES [ BY BIT 11 IN FIELD flags ],
      mutual_contact: YES [ BY BIT 12 IN FIELD flags ],
      deleted: [ SKIPPED BY BIT 13 IN FIELD flags ],
      bot: [ SKIPPED BY BIT 14 IN FIELD flags ],
      bot_chat_history: [ SKIPPED BY BIT 15 IN FIELD flags ],
      bot_nochats: [ SKIPPED BY BIT 16 IN FIELD flags ],
      verified: [ SKIPPED BY BIT 17 IN FIELD flags ],
      restricted: [ SKIPPED BY BIT 18 IN FIELD flags ],
      min: [ SKIPPED BY BIT 20 IN FIELD flags ],
      bot_inline_geo: [ SKIPPED BY BIT 21 IN FIELD flags ],
      support: [ SKIPPED BY BIT 23 IN FIELD flags ],
      scam: [ SKIPPED BY BIT 24 IN FIELD flags ],
      apply_min_photo: [ SKIPPED BY BIT 25 IN FIELD flags ],
      fake: [ SKIPPED BY BIT 26 IN FIELD flags ],
      bot_attach_menu: [ SKIPPED BY BIT 27 IN FIELD flags ],
      premium: [ SKIPPED BY BIT 28 IN FIELD flags ],
      attach_menu_enabled: [ SKIPPED BY BIT 29 IN FIELD flags ],
      id: 136909646 [LONG],
      access_hash: 4884274740030210701 [LONG],
      first_name: "Ppp8" [STRING],
      last_name: [ SKIPPED BY BIT 2 IN FIELD flags ],
      username: "eertyu" [STRING],
      phone: [ SKIPPED BY BIT 4 IN FIELD flags ],
      photo: [ SKIPPED BY BIT 5 IN FIELD flags ],
      status: { userStatusOffline
        was_online: 1681565312 [INT],
      },
      bot_info_version: [ SKIPPED BY BIT 14 IN FIELD flags ],
      restriction_reason: [ SKIPPED BY BIT 18 IN FIELD flags ],
      bot_inline_placeholder: [ SKIPPED BY BIT 19 IN FIELD flags ],
      lang_code: [ SKIPPED BY BIT 22 IN FIELD flags ],
      emoji_status: [ SKIPPED BY BIT 30 IN FIELD flags ],
    },
  ],
},