{message
  flags: 0 [INT],
  out: [ SKIPPED BY BIT 1 IN FIELD flags ],
  mentioned: [ SKIPPED BY BIT 4 IN FIELD flags ],
  media_unread: [ SKIPPED BY BIT 5 IN FIELD flags ],
  silent: [ SKIPPED BY BIT 13 IN FIELD flags ],
  post: [ SKIPPED BY BIT 14 IN FIELD flags ],
  from_scheduled: [ SKIPPED BY BIT 18 IN FIELD flags ],
  legacy: [ SKIPPED BY BIT 19 IN FIELD flags ],
  edit_hide: [ SKIPPED BY BIT 21 IN FIELD flags ],
  pinned: [ SKIPPED BY BIT 24 IN FIELD flags ],
  noforwards: [ SKIPPED BY BIT 26 IN FIELD flags ],
  id: 2 [INT],
  from_id: [ SKIPPED BY BIT 8 IN FIELD flags ],
  peer_id: { peerUser
    user_id: 136909646 [LONG],
  },
  fwd_from: [ SKIPPED BY BIT 2 IN FIELD flags ],
  via_bot_id: [ SKIPPED BY BIT 11 IN FIELD flags ],
  reply_to: [ SKIPPED BY BIT 3 IN FIELD flags ],
  date: 1681461073 [INT],
  message: "你好啊" [STRING],
  media: [ SKIPPED BY BIT 9 IN FIELD flags ],
  reply_markup: [ SKIPPED BY BIT 6 IN FIELD flags ],
  entities: [ SKIPPED BY BIT 7 IN FIELD flags ],
  views: [ SKIPPED BY BIT 10 IN FIELD flags ],
  forwards: [ SKIPPED BY BIT 10 IN FIELD flags ],
  replies: [ SKIPPED BY BIT 23 IN FIELD flags ],
  edit_date: [ SKIPPED BY BIT 15 IN FIELD flags ],
  post_author: [ SKIPPED BY BIT 16 IN FIELD flags ],
  grouped_id: [ SKIPPED BY BIT 17 IN FIELD flags ],
  reactions: [ SKIPPED BY BIT 20 IN FIELD flags ],
  restriction_reason: [ SKIPPED BY BIT 22 IN FIELD flags ],
  ttl_period: [ SKIPPED BY BIT 25 IN FIELD flags ],
}